### ISSUE TITLE
Ionic and this plugin

### ISSUE THREAD

**Issue by vkocjancic** [loicknuchel/cordova-device-accounts#2]
I have instlaled this plugin and am trying to use it with Ionic framework. When I call cordova.plugins.DeviceAccounts, I get undefined. Any ideas?

**Comment by vkocjancic** [comment]
Solved it. you should call DaviceAccounts methods like this: plugins.DeviceAccounts.function and not cordova.plugins.DeviceAccounts.function.

**Comment by loicknuchel** [comment]
Sorry, I have one error on my README...

**Comment by vkocjancic** [comment]
Why don't you just set plugin to use what all other plugins use cordova.plugins.xy?

**Comment by loicknuchel** [comment]
There is not much plugins using cordova.plugins.xxx but I think it's the best place to put the plugin API.
So, I should switch...
